### ISSUE TITLE
DAG carburants

### ISSUE THREAD

**Issue by geoffreyaldebert** [datagouv/datagouvfr_data_pipelines#3]
Développer un DAG pour la gestion des données carburants.
Aujourd'hui les données sont directement stockées dans un dépôt prix-carburants-data. Il faudrait plutôt utiliser minio pour ce stockage de données.

**Comment by Pierlou** [comment]
Ca a été fait ? cf https://github.com/etalab/datagouvfr_data_pipelines/blob/8f6f50b99f1f93d6cecd2bf8c696f73582e8a267/data_processing/carburants/task_functions.py#L98
