### ISSUE TITLE
s'affranchir des operator custom pour n'utiliser que des utils

### ISSUE THREAD

**Issue by geoffreyaldebert** [datagouv/datagouvfr_data_pipelines#5]
Pour une meilleure portabilité, enlever du dépôt l'utilisation des opérateurs customs présent sur le [dépôt de la stack data-engineering](https://github.com/etalab/data-engineering-stack)

**Comment by Pierlou** [comment]
Initié ici : https://github.com/etalab/datagouvfr_data_pipelines/pull/93
Les notebooks générés par le `PapermillMinioOperator` dans le DAG `digest` sont toujours consultés par l'équipe, à voir si on veut le garder ou changer de moyen de reporting

**Comment by Pierlou** [comment]
Done ✅ On peut enlever les opérateurs customs de la stack
